version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql_order_service
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - microservices_order_service:/var/lib/mysql

volumes:
  microservices_order_service: