spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order-service?sslMode=DISABLED&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8081
  error:
    include-stacktrace: ON_PARAM

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: ALWAYS

# Resilience4J poperties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      inventory:
        timeoutDuration: 3s
  retry:
    instances:
      inventory:
        maxAttempts: 3
        waitDuration: 5s
