spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/product-service?authSource=admin
  application:
    name: product-service
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

