spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory-service?sslMode=DISABLED&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 0
  error:
    include-stacktrace: ON_PARAM

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
